### PR TITLE
feat: Add a possibility for a forced GPS cache update

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Related to https://github.com/appium/appium/issues/16238

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Could you please help with testing on real devices?

**Comment by KazuCocoa** [comment]
ok, will do

**Comment by KazuCocoa** [comment]
sorry late, but will do. (I don't forget this pr)

**Comment by mykola-mokhnach** [comment]
There is no rush on it @KazuCocoa 
Thanks for spending your time

**Comment by KazuCocoa** [comment]
Should we get the updated location _after_ calling `forceUpdate`? (The updated readme addressed `asynchronously`, so I guessed this async behavior was expected)

So, initially `adb shell am broadcast -a io.appium.settings.location -n io.appium.settings/.receivers.LocationInfoReceiver` returned `data="37.3950818 -122.0992575 -5.1999998"`.

Then, `adb shell am broadcast -a io.appium.settings.location -n io.appium.settings/.receivers.LocationInfoReceiver --ez forceUpdate true` returned the same `data="37.3950818 -122.0992575 -5.1999998"` after moving the testing real device a bit.

```
12-26 18:43:20.599  1566  1805 D CompatibilityInfo: applicationScale - 1.0
12-26 18:43:20.601 22323 22323 D LocationInfoReceiver: Getting current location
12-26 18:43:20.601 22323 22323 D LocationInfoReceiver: Initiating forced location update
12-26 18:43:20.602 22323 22323 D LocationTracker: The cached location has been successfully retrieved
12-26 18:43:20.628  4780  5015 I PlayCommon: [233] aaor.k(200): Successfully uploaded logs.
```

Once I called `adb shell am broadcast -a io.appium.settings.location -n io.appium.settings/.receivers.LocationInfoReceiver` again, it returned updated `data="37.3951009 -122.0992513 -5.4000001"`

```
12-26 18:43:22.612 22871 24677 I Finsky:background: [1190] hsa.f(1): getDownloads()
12-26 18:43:22.613  4780  4780 I Finsky  : [2] jst.u(5): Installer::IT: com.aa.android to state 40
12-26 18:43:22.625  4780  4899 I Finsky  : [219] jsg.accept(3): Installer::IT: starting next download: package=com.aa.android
12-26 18:43:22.627  4780  4780 I Finsky  : [2] hug.h(1): remove(11741)
12-26 18:43:22.630 22871 24677 I Finsky:background: [1190] hsa.g(1): remove(request_id=11741)
12-26 18:43:22.686 22323 22323 D LocationTracker: Got a location update from Play Services
12-26 18:43:22.690 22323 22323 D LocationTracker: The current location has been successfully retrieved from Play Services
12-26 18:43:22.691  1566  1805 D CompatibilityInfo: mCompatibilityFlags - 0
12-26 18:43:22.691  1566  1805 D CompatibilityInfo: applicationDensity - 420
12-26 18:43:22.691  1566  1805 D CompatibilityInfo: applicationScale - 1.0
12-26 18:43:22.693 22323 22323 D LocationInfoReceiver: Getting current location
12-26 18:43:22.693 22323 22323 D LocationTracker: The cached location has been successfully retrieved
12-26 18:43:22.724 22871 24318 I Finsky:background: [1184] hsa.d(20): onRemove(request_id=11741, files_to_download=1, group_id=com.aa.android, display_data[invisible=false, title=American Airlines], network_restrictions=1, status=succeeded, bytes_downloaded=2631, retry[count=0, next_retry=n/a])
```

Tested device was Android 10.

**Comment by mykola-mokhnach** [comment]
> Should we get the updated location after calling forceUpdate? (The updated readme addressed asynchronously, so I guessed this async behavior was expected)

Yes, such behaviour is expected. I was not able to find any way to block the broadcast call until coordinates are actually refreshed.

> Tested device was Android 10.

Do you have a possibility to test it with an older device, for example Android 7?

**Comment by KazuCocoa** [comment]
Quickly tested on android 6.
It seems the data did not get up-to-date without killing the settings app process once in both with/without this PR.

I haven't checked adb logcat etc yet. Will take a look later again.

```
kazuaki@kazus-MB-pro debug % adb shell am broadcast -a io.appium.settings.location -n io.appium.settings/.receivers.LocationInfoReceiver
Broadcasting: Intent { act=io.appium.settings.location cmp=io.appium.settings/.receivers.LocationInfoReceiver }
Broadcast completed: result=-1, data="37.3950876 -122.0992612 -5.4000001"

# moved the device
kazuaki@kazus-MB-pro debug % adb shell am broadcast -a io.appium.settings.location -n io.appium.settings/.receivers.LocationInfoReceiver
Broadcasting: Intent { act=io.appium.settings.location cmp=io.appium.settings/.receivers.LocationInfoReceiver }
Broadcast completed: result=-1, data="37.3950876 -122.0992612 -5.4000001"

# kill the process once
kazuaki@kazus-MB-pro debug % adb shell am broadcast -a io.appium.settings.location -n io.appium.settings/.receivers.LocationInfoReceiver
Broadcasting: Intent { act=io.appium.settings.location cmp=io.appium.settings/.receivers.LocationInfoReceiver }
Broadcast completed: result=-1, data="37.3950822 -122.0992440 0.0000000"
kazuaki@kazus-MB-pro debug % adb shell am broadcast -a io.appium.settings.location -n io.appium.settings/.receivers.LocationInfoReceiver
Broadcasting: Intent { act=io.appium.settings.location cmp=io.appium.settings/.receivers.LocationInfoReceiver }
Broadcast completed: result=-1, data="37.3950822 -122.0992440 -5.5000000"
```

**Comment by mykola-mokhnach** [comment]
Try to also supply `forceUpdate` for Android 6. Default settings for automated coordinates refresh are quite relaxed there to preserve the phone battery life.

**Comment by KazuCocoa** [comment]
seems better. When I charged the device battery fully, the `forceUpdate` worked on Android v6.
(I just tried with less than half before in https://github.com/appium/io.appium.settings/pull/76#issuecomment-1001700670)

**Review by KazuCocoa — APPROVED** [review]

**Pull request merged**
