### PR TITLE
Start foreground service by calling proper method

### PR DESCRIPTION
**Pull request by gpiszczek**
Fixes appium/appium#13736 . Now tests on Xiaomi A1 phone start without problems.

Needs testing on other real devices.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/13736

**Comment by KazuCocoa** [comment]
@mykola-mokhnach 
What do you think to merge this?
I read AOSP a bit about the difference, but almost the same.
So, if this worked on some Android phones (maybe a bit customised??) like Xiaomi which did not work with simple `startService`, we can apply this.
(`startService` works on my Android 9 phone tho)

**Comment by mykola-mokhnach** [comment]
I'm afraid I don't have enough expertise on this. :(
@pr4bh4sh Could you please review this PR?

**Comment by KazuCocoa** [comment]
Btw, will take a look AOSP more later. I found a flag. So, dig in it more

**Comment by pr4bh4sh** [comment]
@mykola-mokhnach I think the PR changes should be fine and it's highly unlikely that It will break anything. ref. https://developer.android.com/guide/components/services#StartingAService

I can verify it on Monday with on emulators and few real devices including with MI OS.

I 100% agree with @KazuCocoa comment  https://github.com/appium/appium/issues/13736#issuecomment-568139117 about the custom implementations and security restrictions/limitation from the device vendor, especially on MI OS. For heavily customised OS like MI and other, we run automation test on a case to case basis at my current workplace. Probably thats why I never encountered it.

**Comment by mykola-mokhnach** [comment]
Thanks for the update @pr4bh4sh

**Comment by KazuCocoa** [comment]
`startForegroundService` passes a flag to run service as foreground. It affects like below lines.
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/am/ActiveServices.java;l=564-573?q=ActiveServices.java&ss=android%2Fplatform%2Fsuperproject

I read around there and related code lines, then it seemed devices which restricted `allowed-to-start policy`? required this `startForegroundService`'s flag to launch the foreground service correctly.

So, maybe the Xiaomi phone was restricted more than other devices we tested before.

**Pull request merged**
