### PR TITLE
Update .npmignore to exclude the unnecessary stuff

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This will allow to save ~100 MB (!) while publishing the package to npm

### CODE REVIEW

**Comment by imurchie** [comment]
Do we need anything other than the apk?

**Comment by imurchie** [comment]
With this change we will get:
```
npm notice
npm notice 📦  io.appium.settings@2.7.0
npm notice === Tarball Contents ===
npm notice 588B   package.json
npm notice 301B   build.gradle
npm notice 3.9kB  build.xml
npm notice 5.0kB  gradlew
npm notice 2.4kB  gradlew.bat
npm notice 158B   index.js
npm notice 10.3kB LICENSE
npm notice 4.7kB  README.md
npm notice 15B    settings.gradle
npm notice 873B   app/build.gradle
npm notice 49.1kB app/build/outputs/apk/settings_apk-debug.apk
npm notice 13.5kB app/build/outputs/logs/manifest-merger-debug-report.txt
npm notice 4.0kB  app/src/main/AndroidManifest.xml
npm notice 5.2kB  app/src/main/java/io/appium/settings/AppiumIME.java
npm notice 4.0kB  app/src/main/java/io/appium/settings/GPSTracker.java
npm notice 2.1kB  app/src/main/java/io/appium/settings/handlers/AbstractSettingHandler.java
npm notice 2.6kB  app/src/main/java/io/appium/settings/handlers/AnimationSettingHandler.java
npm notice 6.1kB  app/src/main/java/io/appium/settings/handlers/DataConnectionSettingHandler.java
npm notice 3.1kB  app/src/main/java/io/appium/settings/handlers/LocaleSettingHandler.java
npm notice 1.3kB  app/src/main/java/io/appium/settings/handlers/WiFiConnectionSettingHandler.java
npm notice 2.6kB  app/src/main/java/io/appium/settings/LocationService.java
npm notice 1.7kB  app/src/main/java/io/appium/settings/MockLocationProvider.java
npm notice 2.2kB  app/src/main/java/io/appium/settings/receivers/AbstractSettingReceiver.java
npm notice 1.0kB  app/src/main/java/io/appium/settings/receivers/AnimationSettingReceiver.java
npm notice 1.1kB  app/src/main/java/io/appium/settings/receivers/DataConnectionSettingReceiver.java
npm notice 2.3kB  app/src/main/java/io/appium/settings/receivers/LocaleSettingReceiver.java
npm notice 1.8kB  app/src/main/java/io/appium/settings/receivers/LocationInfoReceiver.java
npm notice 1.1kB  app/src/main/java/io/appium/settings/receivers/WiFiConnectionSettingReceiver.java
npm notice 1.3kB  app/src/main/java/io/appium/settings/Settings.java
npm notice 2.9kB  app/src/main/java/io/appium/settings/Unlock.java
npm notice 9.4kB  app/src/main/res/drawable-hdpi/ic_launcher.png
npm notice 2.7kB  app/src/main/res/drawable-ldpi/ic_launcher.png
npm notice 5.2kB  app/src/main/res/drawable-mdpi/ic_launcher.png
npm notice 14.4kB app/src/main/res/drawable-xhdpi/ic_launcher.png
npm notice 1.3kB  app/src/main/res/layout/main.xml
npm notice 213B   app/src/main/res/values/dimens.xml
npm notice 398B   app/src/main/res/values/strings.xml
npm notice 116B   app/src/main/res/xml/method.xml
npm notice 53.6kB gradle/wrapper/gradle-wrapper.jar
npm notice 230B   gradle/wrapper/gradle-wrapper.properties
npm notice === Tarball Details ===
npm notice name:          io.appium.settings
npm notice version:       2.7.0
npm notice filename:      io.appium.settings-2.7.0.tgz
npm notice package size:  149.8 kB
npm notice unpacked size: 224.7 kB
npm notice shasum:        a8f48989de39ffe6e4fc96efdfecee164c958054
npm notice integrity:     sha512-r1n726UkI5DzW[...]GzCRF6tzY6hew==
npm notice total files:   40
npm notice
io.appium.settings-2.7.0.tgz
```

**Comment by imurchie** [comment]
If you did:
```diff
diff --git a/.npmignore b/.npmignore
deleted file mode 100644
index 81ceef0..0000000
--- a/.npmignore
+++ /dev/null
@@ -1,3 +0,0 @@
-bin/*
-!bin/settings_apk-debug.apk
-gen
diff --git a/package.json b/package.json
index 8ae3e70..6d765b0 100644
--- a/package.json
+++ b/package.json
@@ -15,6 +15,10 @@
     "android",
     "settings"
   ],
+  "files": [
+    "index.js",
+    "app/build/outputs/apk/settings_apk-debug.apk"
+  ],
   "author": "https://github.com/appium",
   "license": "Apache-2.0",
   "bugs": {
```
It would produce:
```
npm notice
npm notice 📦  io.appium.settings@2.7.0
npm notice === Tarball Contents ===
npm notice 673B   package.json
npm notice 158B   index.js
npm notice 10.3kB LICENSE
npm notice 4.7kB  README.md
npm notice 49.1kB app/build/outputs/apk/settings_apk-debug.apk
npm notice === Tarball Details ===
npm notice name:          io.appium.settings
npm notice version:       2.7.0
npm notice filename:      io.appium.settings-2.7.0.tgz
npm notice package size:  53.5 kB
npm notice unpacked size: 64.9 kB
npm notice shasum:        4dd5da4c87a1ad0bca42f2b2ad5c7a82252d066c
npm notice integrity:     sha512-w6JgeHft2GvaF[...]weuVRF/AM0u9w==
npm notice total files:   5
npm notice
io.appium.settings-2.7.0.tgz
```

**Comment by mykola-mokhnach** [comment]
@imurchie I'd like to keep the sources. They aren't so large

**Comment by imurchie** [comment]
Ok. But it should all be done in `package.json` not `.npmignore` (see https://blog.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish for some of the issues with `.npmignore`).

**Comment by imurchie** [comment]
This seems to leave a lot of extraneous stuff:
```
npm notice
npm notice 📦  io.appium.settings@2.7.0
npm notice === Tarball Contents ===
npm notice 679B    package.json
npm notice 301B    build.gradle
npm notice 5.0kB   gradlew
npm notice 2.4kB   gradlew.bat
npm notice 158B    index.js
npm notice 10.3kB  LICENSE
npm notice 4.7kB   README.md
npm notice 15B     settings.gradle
npm notice 22.8kB  .gradle/3.3/taskArtifacts/fileHashes.bin
npm notice 147.0kB .gradle/3.3/taskArtifacts/fileSnapshots.bin
npm notice 92.9kB  .gradle/3.3/taskArtifacts/taskArtifacts.bin
npm notice 17B     .gradle/3.3/taskArtifacts/taskArtifacts.lock
npm notice 24.6kB  .gradle/3.3/tasks/_app_compileDebugJavaWithJavac/localClassSetAnalysis/localClassSetAnalysis.bin
npm notice 17B     .gradle/3.3/tasks/_app_compileDebugJavaWithJavac/localClassSetAnalysis/localClassSetAnalysis.lock
npm notice 18.5kB  .gradle/3.3/tasks/_app_compileDebugJavaWithJavac/localJarClasspathSnapshot/localJarClasspathSnapshot.bin
npm notice 17B     .gradle/3.3/tasks/_app_compileDebugJavaWithJavac/localJarClasspathSnapshot/localJarClasspathSnapshot.lock
npm notice 873B    app/build.gradle
npm notice 443B    app/build/generated/source/buildConfig/debug/io/appium/settings/BuildConfig.java
npm notice 1.3kB   app/build/generated/source/r/debug/io/appium/settings/R.java
npm notice 5.6kB   app/build/intermediates/blame/res/debug/multi/values.json
npm notice 262B    app/build/intermediates/blame/res/debug/single/drawable-hdpi.json
npm notice 262B    app/build/intermediates/blame/res/debug/single/drawable-ldpi.json
npm notice 262B    app/build/intermediates/blame/res/debug/single/drawable-mdpi.json
npm notice 264B    app/build/intermediates/blame/res/debug/single/drawable-xhdpi.json
npm notice 234B    app/build/intermediates/blame/res/debug/single/layout.json
npm notice 232B    app/build/intermediates/blame/res/debug/single/xml.json
npm notice 4.8kB   app/build/intermediates/classes/debug/io/appium/settings/AppiumIME.class
npm notice 711B    app/build/intermediates/classes/debug/io/appium/settings/BuildConfig.class
npm notice 3.2kB   app/build/intermediates/classes/debug/io/appium/settings/GPSTracker.class
npm notice 1.8kB   app/build/intermediates/classes/debug/io/appium/settings/handlers/AbstractSettingHandler.class
npm notice 2.6kB   app/build/intermediates/classes/debug/io/appium/settings/handlers/AnimationSettingHandler.class
npm notice 5.9kB   app/build/intermediates/classes/debug/io/appium/settings/handlers/DataConnectionSettingHandler.class
npm notice 3.2kB   app/build/intermediates/classes/debug/io/appium/settings/handlers/LocaleSettingHandler.class
npm notice 1.2kB   app/build/intermediates/classes/debug/io/appium/settings/handlers/WiFiConnectionSettingHandler.class
npm notice 2.5kB   app/build/intermediates/classes/debug/io/appium/settings/LocationService.class
npm notice 1.6kB   app/build/intermediates/classes/debug/io/appium/settings/MockLocationProvider.class
npm notice 623B    app/build/intermediates/classes/debug/io/appium/settings/R.class
npm notice 340B    app/build/intermediates/classes/debug/io/appium/settings/R$attr.class
npm notice 461B    app/build/intermediates/classes/debug/io/appium/settings/R$dimen.class
npm notice 407B    app/build/intermediates/classes/debug/io/appium/settings/R$drawable.class
npm notice 418B    app/build/intermediates/classes/debug/io/appium/settings/R$id.class
npm notice 394B    app/build/intermediates/classes/debug/io/appium/settings/R$layout.class
npm notice 559B    app/build/intermediates/classes/debug/io/appium/settings/R$string.class
npm notice 387B    app/build/intermediates/classes/debug/io/appium/settings/R$xml.class
npm notice 2.1kB   app/build/intermediates/classes/debug/io/appium/settings/receivers/AbstractSettingReceiver.class
npm notice 852B    app/build/intermediates/classes/debug/io/appium/settings/receivers/AnimationSettingReceiver.class
npm notice 877B    app/build/intermediates/classes/debug/io/appium/settings/receivers/DataConnectionSettingReceiver.class
npm notice 2.0kB   app/build/intermediates/classes/debug/io/appium/settings/receivers/LocaleSettingReceiver.class
npm notice 1.7kB   app/build/intermediates/classes/debug/io/appium/settings/receivers/LocationInfoReceiver.class
npm notice 877B    app/build/intermediates/classes/debug/io/appium/settings/receivers/WiFiConnectionSettingReceiver.class
npm notice 1.1kB   app/build/intermediates/classes/debug/io/appium/settings/Settings.class
npm notice 652B    app/build/intermediates/classes/debug/io/appium/settings/Settings$1.class
npm notice 2.8kB   app/build/intermediates/classes/debug/io/appium/settings/Unlock.class
npm notice 26B     app/build/intermediates/incremental-safeguard/debug/tag.txt
npm notice 5B      app/build/intermediates/incremental/compileDebugAidl/dependency.store
npm notice 397B    app/build/intermediates/incremental/mergeDebugAssets/merger.xml
npm notice 298B    app/build/intermediates/incremental/mergeDebugJniLibFolders/merger.xml
npm notice 1.2kB   app/build/intermediates/incremental/mergeDebugResources/compile-file-map.properties
npm notice 503B    app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
npm notice 2.6kB   app/build/intermediates/incremental/mergeDebugResources/merger.xml
npm notice 298B    app/build/intermediates/incremental/mergeDebugShaders/merger.xml
npm notice 298B    app/build/intermediates/incremental/packageDebug/dex-renamer-state.txt
npm notice 2.3kB   app/build/intermediates/incremental/packageDebug/file-input-save-data.txt
npm notice 32.7kB  app/build/intermediates/incremental/packageDebug/zip-cache/lBSkidTFV24IFmgIeE_Kty6UPK4=
npm notice 4.3kB   app/build/intermediates/manifests/full/debug/AndroidManifest.xml
npm notice 7.9kB   app/build/intermediates/res/merged/debug/drawable-hdpi/ic_launcher.png
npm notice 2.4kB   app/build/intermediates/res/merged/debug/drawable-ldpi/ic_launcher.png
npm notice 4.5kB   app/build/intermediates/res/merged/debug/drawable-mdpi/ic_launcher.png
npm notice 12.1kB  app/build/intermediates/res/merged/debug/drawable-xhdpi/ic_launcher.png
npm notice 1.3kB   app/build/intermediates/res/merged/debug/layout/main.xml
npm notice 503B    app/build/intermediates/res/merged/debug/values/values.xml
npm notice 116B    app/build/intermediates/res/merged/debug/xml/method.xml
npm notice 32.7kB  app/build/intermediates/res/resources-debug.ap_
npm notice 26.7kB  app/build/intermediates/transforms/dex/debug/folders/1000/1f/main/classes.dex
npm notice 49.1kB  app/build/outputs/apk/settings_apk-debug.apk
npm notice 13.5kB  app/build/outputs/logs/manifest-merger-debug-report.txt
npm notice 4.0kB   app/src/main/AndroidManifest.xml
npm notice 5.2kB   app/src/main/java/io/appium/settings/AppiumIME.java
npm notice 4.0kB   app/src/main/java/io/appium/settings/GPSTracker.java
npm notice 2.1kB   app/src/main/java/io/appium/settings/handlers/AbstractSettingHandler.java
npm notice 2.6kB   app/src/main/java/io/appium/settings/handlers/AnimationSettingHandler.java
npm notice 6.1kB   app/src/main/java/io/appium/settings/handlers/DataConnectionSettingHandler.java
npm notice 3.1kB   app/src/main/java/io/appium/settings/handlers/LocaleSettingHandler.java
npm notice 1.3kB   app/src/main/java/io/appium/settings/handlers/WiFiConnectionSettingHandler.java
npm notice 2.6kB   app/src/main/java/io/appium/settings/LocationService.java
npm notice 1.7kB   app/src/main/java/io/appium/settings/MockLocationProvider.java
npm notice 2.2kB   app/src/main/java/io/appium/settings/receivers/AbstractSettingReceiver.java
npm notice 1.0kB   app/src/main/java/io/appium/settings/receivers/AnimationSettingReceiver.java
npm notice 1.1kB   app/src/main/java/io/appium/settings/receivers/DataConnectionSettingReceiver.java
npm notice 2.3kB   app/src/main/java/io/appium/settings/receivers/LocaleSettingReceiver.java
npm notice 1.8kB   app/src/main/java/io/appium/settings/receivers/LocationInfoReceiver.java
npm notice 1.1kB   app/src/main/java/io/appium/settings/receivers/WiFiConnectionSettingReceiver.java
npm notice 1.3kB   app/src/main/java/io/appium/settings/Settings.java
npm notice 2.9kB   app/src/main/java/io/appium/settings/Unlock.java
npm notice 9.4kB   app/src/main/res/drawable-hdpi/ic_launcher.png
npm notice 2.7kB   app/src/main/res/drawable-ldpi/ic_launcher.png
npm notice 5.2kB   app/src/main/res/drawable-mdpi/ic_launcher.png
npm notice 14.4kB  app/src/main/res/drawable-xhdpi/ic_launcher.png
npm notice 1.3kB   app/src/main/res/layout/main.xml
npm notice 213B    app/src/main/res/values/dimens.xml
npm notice 398B    app/src/main/res/values/strings.xml
npm notice 116B    app/src/main/res/xml/method.xml
npm notice 53.6kB  gradle/wrapper/gradle-wrapper.jar
npm notice 230B    gradle/wrapper/gradle-wrapper.properties
npm notice === Tarball Details ===
npm notice name:          io.appium.settings
npm notice version:       2.7.0
npm notice filename:      io.appium.settings-2.7.0.tgz
npm notice package size:  296.5 kB
npm notice unpacked size: 712.7 kB
npm notice shasum:        c34b45c013e5df739cfef034ce30cf2e89c03309
npm notice integrity:     sha512-KWSoOLDs6aHps[...]HtROs7LSdWq4A==
npm notice total files:   104
npm notice
io.appium.settings-2.7.0.tgz
```

**Comment by imurchie** [comment]
Just as a note, you can see what _will_ be in the tarball using `npm pack --dry-run`.

**Comment by mykola-mokhnach** [comment]
@imurchie how about now?

**Pull request merged**
