### PR TITLE
Port UnicodeIME helper into the current package

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This will allow to save time for session init by having all helpers in a single apk

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@imurchie I assume we don't use here any of the components mentioned in this notice file

**Comment by imurchie** [comment]
Yes, the entire UnicodeIME is a re-worked version of it. It needs to be there. He has threatened action before.

**Comment by mykola-mokhnach** [comment]
ok, added

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Added a new caption to README

**Pull request merged**
