### PR TITLE
refactor!: Remove the obsolete Unlocker activity

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
BREAKING CHANGE: Removed the obsolete Unlocker activity. This hack in this activity was only properly working for Android below API 21
BREAKING CHANGE: Bumped the minimum required Android version to 21

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
Makes sense. With this change, i confirmed by Android device did not keep unlock even the settings app was running in the background.

Then, we may need to call keyevent like below (menu) for swipe unlock (afaik, to keep the behavior without both unlockType and unlockKey case )
```
adb shell input keyevent 82
```
https://github.com/appium/appium-android-driver/blob/a3b619e60210686c95ee9fcb6d67cec4388b28d1/lib/android-helpers.js#L769

**Comment by mykola-mokhnach** [comment]
> Makes sense. With this change, i confirmed that an Android device (Android 11) did not keep unlock even the settings app was running in the background.
> 
> Then, we may need to call keyevent like below (menu) for swipe unlock (afaik, to keep the behavior without both unlockType and unlockKey case )
> 
> ```
> adb shell input keyevent 82
> ```
> 
> https://github.com/appium/appium-android-driver/blob/a3b619e60210686c95ee9fcb6d67cec4388b28d1/lib/android-helpers.js#L769

I was actually going to call `adb.dismissKeyguard()` helper in appium-android after this change is published

**Comment by KazuCocoa** [comment]
I wondered if something notification stuff existed on the screen,  the touchscreen swipe in `dismissKeyguard` did not unlock swipe well to unlock the screen (need to check tho)

**Comment by mykola-mokhnach** [comment]
> I wondered if something notification stuff existed on the screen, the touchscreen swipe in `dismissKeyguard` did not unlock swipe well to unlock the screen (need to check tho)

I assume https://github.com/appium/appium-adb/blob/1aebc41ae76070bd8973c2fbabfb2e696b082f41/lib/tools/lockmgmt.js#L233 should do the trick. However it's only applied to Android 5. Newer versions simply call `wm dismiss-keyguard` shell command

**Comment by KazuCocoa** [comment]
Oh, yea. I saw only your diff on the another GitHub PR, thus did not aware of the api version thing

**Pull request merged**
